name: Builder

on:
  repository_dispatch:
    types: [ triger-event ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: dispatch-build
      uses: actions/checkout@v3
    - name: Repository Dispatch subs
      uses: danielr1996/envsubst-action@1.0.0
      env:
        REF_BRANCH: ${{ github.event.client_payload.ref }}
        REF_REPO_SOURCE: ${{ github.event.client_payload.repo_source }}
        REF_PATH: ${{ github.event.client_payload.config_path }}
      with:
        input: skaffold.yaml
        output: skaffold.yaml
    - name: check env
      run: cat skaffold.yaml
    - name: Skaffold build
      uses: hiberbee/github-action-skaffold@1.19.0
      with:
        skaffold-version: 2.13.2
        command: build
