name: Builder

on:
  repository_dispatch:
    types: [ triger-event ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: dispatch-build
      uses: actions/checkout@v3
    - name: Repository Dispatch subs
      uses: dominicwatson/github-action-envsubst@v1
      env:
        REF_BRANCH: ${{ github.event.client_payload.ref }}
        REF_REPO_SOURCE: ${{ github.event.client_payload.repo_source }}
        REF_CONFIG_PATH: ${{ github.event.client_payload.config_path }}
      with:
        files: skaffold.yaml
        patterns: $REF_REPO_SOURCE $REF_CONFIG_PATH $REF_BRANCH
    - name: check env
      run: ls -a && cat skaffold.yaml
    - name: Skaffold build
      uses: hiberbee/github-action-skaffold@1.19.0
      with:
        skaffold-version: 2.13.2
        command: build
